Repository riganti/dotvvm, pull requests merged in 2021-07, with the labels that each got.

#1065 Fixed implementations of `GetNodes` and `GetChildNodes`
  src/DotVVM.Framework.Tests/Binding/BindingCompilationTests.cs
  src/DotVVM.Framework/Compilation/Parser/Binding/Parser/FormattedBindingParserNode.cs
  src/DotVVM.Framework/Compilation/Parser/Binding/Parser/InterpolatedStringBindingParserNode.cs
  src/DotVVM.Framework/Compilation/Parser/Binding/Parser/LambdaBindingParserNode.cs
  src/DotVVM.Framework/Compilation/Parser/Binding/Parser/TypeOrFunctionReferenceBindingParserNode.cs
  src/DotVVM.Framework/Compilation/Parser/Binding/Parser/TypeReferenceBindingParserNode.cs
Labels: Visual Studio Extension

#1076 DotVVM error page ignores error from subsequent middlewares
  src/DotVVM.Framework.Hosting.AspNetCore/ApplicationBuilderExtensions.cs
  src/DotVVM.Framework.Hosting.AspNetCore/DotVVM.Framework.Hosting.AspNetCore.csproj
  src/DotVVM.Framework.Hosting.AspNetCore/Hosting/Middlewares/DotvvmErrorPageMiddleware.cs
  src/DotVVM.Framework.Hosting.AspNetCore/Hosting/Middlewares/DotvvmMiddleware.cs
  src/DotVVM.Framework.Hosting.Owin/AppBuilderExtensions.cs
  src/DotVVM.Framework.Hosting.Owin/DotVVM.Framework.Hosting.Owin.csproj
  src/DotVVM.Framework.Hosting.Owin/Hosting/Middlewares/DotvvmMiddleware.cs
  src/DotVVM.Framework/DependencyInjection/DotVVMServiceCollectionExtensions.cs
  src/DotVVM.Framework/DotVVM.Framework.csproj
  src/DotVVM.Framework/Hosting/ErrorPages/DotvvmErrorPageRenderer.cs
Labels: Framework, enhancement

#1068 Fixed issues with string interpolation
  src/DotVVM.Framework.Tests/Binding/JavascriptCompilationTests.cs
  src/DotVVM.Framework.Tests/Parser/Binding/BindingTokenizerTests.cs
  src/DotVVM.Framework/Compilation/Javascript/JavascriptTranslatableMethodCollection.cs
  src/DotVVM.Framework/Compilation/Parser/Binding/Parser/BindingParser.cs
  src/DotVVM.Framework/Compilation/Parser/Binding/Tokenizer/BindingTokenizer.cs
  src/DotVVM.Framework/Resources/Scripts/DotVVM.Globalize.ts
  src/DotVVM.Framework/Resources/Scripts/utils/stringHelper.ts
  src/DotVVM.Samples.BasicSamples.Owin/package-lock.json
  src/DotVVM.Samples.Common/DotVVM.Samples.Common.csproj
  src/DotVVM.Samples.Common/ViewModels/FeatureSamples/StringInterpolation/StringInterpolationViewModel.cs
  src/DotVVM.Samples.Common/Views/FeatureSamples/StringInterpolation/StringInterpolation.dothtml
  src/DotVVM.Samples.Tests/Feature/StringInterpolationTests.cs
  src/DotVVM.Testing.Abstractions/SamplesRouteUrls.designer.cs
Labels: bug
